(() => { const header=document.querySelector('.site-header'), menu=document.querySelector('.menu-toggle'), nav=document.querySelector('.nav'), top=document.querySelector('.back-top');
const setScroll=()=>{header?.classList.toggle('scrolled',scrollY>8);top?.classList.toggle('show',scrollY>500)};addEventListener('scroll',setScroll,{passive:true});setScroll();
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a:not(.btn)').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===page));
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.portfolio-card').forEach(c=>c.classList.toggle('hidden',f!=='all'&&!c.dataset.categories.includes(f)))}));
document.querySelectorAll('.faq-question').forEach(q=>q.addEventListener('click',()=>{const item=q.parentElement,open=item.classList.toggle('open');q.setAttribute('aria-expanded',open)}));
const heroVideo=document.querySelector('#hero-video');heroVideo?.addEventListener('loadeddata',()=>{heroVideo.classList.add('has-video');heroVideo.play().catch(()=>{})});heroVideo?.addEventListener('error',()=>heroVideo.classList.remove('has-video'));
const form=document.querySelector('#contact-form');form?.addEventListener('submit',e=>{e.preventDefault();let valid=true;form.querySelectorAll('[required]').forEach(x=>{if(!x.value.trim()){valid=false;x.setAttribute('aria-invalid','true')}else x.removeAttribute('aria-invalid')});if(valid){form.reset();document.querySelector('.form-message').style.display='block'}});
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));})();
